// Code generated by mklinknames.awk. DO NOT EDIT.

package user

import _ "unsafe"

//go:linkname libc_getpwnam_r getpwnam_r
//go:linkname libc_getpwuid_r getpwuid_r
//go:linkname libc_getgrnam_r getgrnam_r
//go:linkname libc_getgrgid_r getgrgid_r
//go:linkname libc_getgrouplist getgrouplist
//go:linkname getGroupList getgrouplist
