// Code generated by mklinknames.awk. DO NOT EDIT.

package runtime

import _ "unsafe"

//go:linkname libcPipe pipe
//go:linkname libcPipe2 pipe2
//go:linkname mincore mincore
//go:linkname sigaction sigaction
//go:linkname sigprocmask sigprocmask
//go:linkname sigfillset sigfillset
//go:linkname sigemptyset sigemptyset
//go:linkname c_sigaddset sigaddset
//go:linkname c_sigdelset sigdelset
//go:linkname sigaltstack sigaltstack
//go:linkname raise raise
//go:linkname getpid getpid
//go:linkname kill kill
//go:linkname setitimer setitimer
//go:linkname exit exit
